module.exports = function(nga, admin) {
  return nga.menu()
    .addChild(nga.menu(admin.getEntity('ordenes'))
      .title('Órdenes')
      .icon('<span class="fa fa-shopping-cart fa-fw"></span>')
      .active(path => path.indexOf('/ordenes') === 0)
      .addChild(nga.menu()
        .title('Crear Pedido')
        .link('/ordenes/create')
        .icon('<span class="fa fa-credit-card fa-fw"></span>'))
      .addChild(nga.menu()
        .title('En Cola')
        .link('/ordenes/list?search={"estado":"encola"}')
        .icon('<span class="fa fa-hourglass fa-fw"></span>'))
      .addChild(nga.menu()
        .title('En Recolección')
        .link('/ordenes/list?search={"estado":"enrecoleccion"}')
        .icon('<span class="fa fa-truck fa-fw"></span>'))
      .addChild(nga.menu()
        .title('En Proceso')
        .link('/ordenes/list?search={"estado":"enproceso"}')
        .icon('<span class="fa fa-repeat fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Finalizadas')
        .link('/ordenes/list?search={"estado":"finalizada"}')
        .icon('<span class="fa fa-check fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Cancelaciones')
        .link('/ordenes/list?search={"estado":"cancelada"}')
        .icon('<span class="fa fa-close fa-fw"></span>'))
    )
    .addChild(nga.menu()
      .title('Facturación')
      .link('/ordenes/list?search={"estado":"rutaEntrega"}')
      .icon('<span class="fa fa-usd fa-fw"></span>')
      .addChild(nga.menu()
        .title('Generar Factura')
        .icon('<span class="fa fa-barcode fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Listado')
        .icon('<span class="fa fa-list fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Anuladas')
        .icon('<span class="fa fa-hand-o-left fa-fw"></span>'))
    )
    .addChild(nga.menu(admin.getEntity('servicios'))
      .icon('<span class="fa fa-phone fa-fw"></span>')
      .addChild(nga.menu()
        .title('Agregar Servicio')
        .icon('<span class="fa fa-plus fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Listado')
        .icon('<span class="fa fa-list fa-fw"></span>'))
    )
    .addChild(nga.menu(admin.getEntity('productos'))
      .icon('<span class="fa fa-industry fa-fw"></span>')
      .addChild(nga.menu()
        .title('Agregar Producto')
        .icon('<span class="fa fa-plus fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Listado')
        .icon('<span class="fa fa-list fa-fw"></span>'))
    )
    .addChild(nga.menu()
      .title('Informes')
      .icon('<span class="fa fa-dashboard fa-fw"></span>')
      .active(path => path.indexOf('/informes') === 0)
      .addChild(nga.menu()
        .title('Facturación')
        .icon('<span class="fa fa-line-chart fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Servicios')
        .icon('<span class="fa fa-area-chart fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Productos')
        .icon('<span class="fa fa-bar-chart fa-fw"></span>'))
    )
    .addChild(nga.menu()
      .title('Usuarios')
      .link('/usuarios/list')
      .icon('<span class="fa fa-users fa-fw"></span>')
      .active(path => path.indexOf('/usuarios') === 0)
      .addChild(nga.menu()
        .title('Crear Usuario')
        .link('/usuarios/create')
        .icon('<span class="fa fa-user-plus fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Listado')
        .link('/usuarios/list')
        .icon('<span class="fa fa-list fa-fw"></span>'))
      // .addChild(nga.menu()
      //   .title('Segments')
      //   .link('/segments') // this state isn't handled by ng-admin - no problem
      //   .active(path => path == '/segments')
      //   .icon('<span class="fa fa-scissors fa-fw"></span>'))
    )
    .addChild(nga.menu()
      .title('Configuración')
      .icon('<span class="fa fa-cog fa-fw"></span>')
      .active(path => path.indexOf('/settings') === 0)
      .addChild(nga.menu()
        .title('Info Empresarial')
        .link('/settings/show/57c4a821e6c05c102a6d969e')
        .icon('<span class="fa fa-id-card-o fa-fw"></span>'))
      .addChild(nga.menu()
        .title('Info Facturas')
        .icon('<span class="fa fa-address-card-o fa-fw"></span>'))
    );
}
